### ISSUE TITLE
Target Relative does not work as expected

### ISSUE THREAD

**Issue by MGGSIDA** [ClimberAB/ClimberKPI#5]
### Description
I have a problem with target mode. Actually it seems that the relative mode does not work for me. I'm using Sense Enterprise June 2017 SR2

Example: KPI : 2050 Target: 2100 Setings within 'Target' "More is better" Banding: "=10"

I would expect to see a Yellow because the KPI is within 10% of Target (actual -2.4%) but the Yellow just comes up when the KPI value is 2091 and it makes no difference if i change the setting from 'relative' to 'absolute'. So it seems to be an absolute limit all the time.

Is there any mistake in the settings I did?

Regards Michael

### Steps to Reproduce
![grafik](https://user-images.githubusercontent.com/23421993/30094760-7c101320-92ce-11e7-9dfb-0a8077dffe48.png)

![grafik](https://user-images.githubusercontent.com/23421993/30094699-08f429da-92ce-11e7-97cf-1edca9ae3f6a.png)

##### Expected behavior

Color changes to yellow

##### Actual behavior

Stays green

### Environment
```
[x] Enterprise June 2017 SR2
```
### Versions

* Extension version: 1.2.0
* Browser: Firefox 52.3.0
* Qlik Sense: June 2017 SR2
* Operating system: Windows 7
* [Other relevant versions]

**Comment by mickeg** [comment]
Hi Michael, thank you for noticing this. You are correct, this is actually a known bug that is fixed in version 1.2.1 which I plan to release during the day! I'll ping you once its up!

//Mikael

**Comment by mickeg** [comment]
@MGGSIDA I have released version 1.2.1 now. Please download that version, make sure to clear your cache and check that you have 1.2.1 in the properties panel.

//Mikael

**Comment by MGGSIDA** [comment]
Now it works. Great support. Thx

**Comment by AndreSyndikus** [comment]
I am using the version 1.4.1 of the extension and this is issue is still the case for me.

![grafik](https://user-images.githubusercontent.com/7046604/38295854-cf148cba-37ef-11e8-9530-1c0c2ecc2598.png)

**Comment by edwardhallgren** [comment]
Hi, In this case you have actual value 100 and target 90, i.e you have reached your target. The banding color will always be green if target is fulfilled.

Br
Edward

**Comment by AndreSyndikus** [comment]
Thanks for the clarification. So i misinterpreted the Banding. I thought it would be like this:

![grafik](https://user-images.githubusercontent.com/7046604/38305139-010552e2-380c-11e8-8131-309d20f24e64.png)
